modLoader = "javafml"
loaderVersion = "[10,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "progressive_smithing"
version = "${version}"
displayName = "Progressive Smithing"
authors = "NellowTCS"
description = '''
Upgrades the Smithing Table to support tier-based armor upgrades.
'''
#logoFile = ""

[[dependencies.progressive_smithing]]
modId = "neoforge"
type = "required"
versionRange = "[21.10,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.progressive_smithing]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.10,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.progressive_smithing]]
modId = "architectury"
type = "required"
versionRange = "[18.0.6,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "progressive_smithing.mixins.json"
